# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('question',),
            },
        ),
        migrations.AlterModelOptions(
            name='reftoken',
            options={'ordering': ('token',)},
        ),
        migrations.AlterField(
            model_name='reftoken',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tokens',
            field=models.ManyToManyField(to='survey.RefToken'),
        ),
    ]
