# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170610_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefQuestion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('question',),
            },
        ),
    ]
