# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_refquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='refquestion',
            name='tokens',
            field=models.ManyToManyField(to='survey.RefToken'),
        ),
    ]
