# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20170610_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refquestion',
            old_name='question',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tokens',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.RefQuestion'),
        ),
    ]
