# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20170611_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.IntegerField()),
                ('no', models.IntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='survey.RefToken')),
            ],
            options={
                'ordering': ('attribute',),
            },
        ),
    ]
