# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20170611_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'User Profile'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.AddField(
            model_name='person',
            name='questions',
            field=models.ManyToManyField(to='survey.RefQuestion'),
        ),
    ]
